= apim samples

image:https://img.shields.io/badge/vert.x-4.3.6-purple.svg[link="https://vertx.io"]

This application provide API sample that I use to play with https://github.com/gravitee-io/gravitee-api-management[Gravite APIM].

== Building

To launch your tests:
----
./gradlew clean test
----

To run your application:
----
./gradlew clean run
----

== Configuration

Configuration is provided through environment variables. Available variables are defined
link:app/src/main/kotlin/io/apim/samples/Configuration.kt[here]

[,java]
----
include::app/src/main/kotlin/io/apim/samples/Configuration.kt[lines=2..]
----

== Available endpoints

It starts 3 http servers

- one used to handle regular HTTP request. (default port 8888)
- one used to handle WebSockets. (default port 8890)
- one used to handle GRPC. (default port 8892)

=== HTTP /echo

This HTTP endpoint can receive HTTP request. It will copy the request received in a 200 response.

==== Example

Using https://httpie.io/cli[httpie]:
----
http POST http://localhost:8888/echo\?qs\=value message=Hello
----

will respond

[source,json]
----
{
    "body": {
        "message": "Hello"
    },
    "headers": {
        "Accept": "application/json, */*;q=0.5",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "keep-alive",
        "Content-Length": "20",
        "Content-Type": "application/json",
        "Host": "localhost:8888",
        "User-Agent": "HTTPie/3.2.1"
    },
    "method": "POST",
    "query_params": {
        "qs": "value"
    }
}
----

=== WebSocket /ws/echo

This endpoint can receive WebSocket request. It will copy the request received in the response.

==== Example

Using https://github.com/vi/websocat[websocat]:
----
websocat -1 ws://localhost:8890/ws/echo
{"message": "Hello"}
----

will respond

[source,json]
----
{
  "type": "json",
  "request": {
    "message": "Hello"
  }
}
----

=== GRPC

The server provide an adapted example of the Route Guide from https://github.com/grpc/grpc-java/tree/master/examples[gRPC examples]

The service shows the various kind of gRPC service calls:

- simple RPC
- server-side streaming RPC
- client-side streaming RPC
- bidirectional streaming RPC

The proto file is available at

- link:app/src/main/resources/grpc/route_guide.proto[here]
- or it can be downloaded using the HTTP server: http://localhost:8888/grpc/route_guide.proto

==== Example

Using https://github.com/fullstorydev/grpcurl[grpcurl].
(The server does not expose Reflection service, therefore we need to provide the protofile to the client)

[source,bash]
----
grpcurl -d '{"latitude": 413628156, "longitude": -749015468}' -import-path app/src/main/resources/grpc -proto route_guide.proto -plaintext localhost:8892 routeguide.RouteGuide/GetFeature
----

will respond

[source,json]
----
{
  "name": "U.S. 6, Shohola, PA 18458, USA",
  "location": {
    "latitude": 413628156,
    "longitude": -749015468
  }
}
----
