{{- if .Values.ingress.http.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $svcName := $fullName -}}
{{- $svcPort := .Values.service.port.http -}}
{{- $ingressPath   := .Values.ingress.http.path -}}
{{- $ingressPathType   := .Values.ingress.http.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.http.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.http.className }}
  ingressClassName: {{ .Values.ingress.http.className }}
  {{- end }}
  rules:
    {{- range $host := .Values.ingress.http.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}

  {{- if .Values.ingress.http.tls }}
  tls:
{{ toYaml .Values.ingress.http.tls | indent 4 }}
  {{- end }}
{{- end }}
