apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.websocket }}
      targetPort: websocket
      protocol: TCP
      name: websocket

  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
