quarkus:
  http:
    host: 0.0.0.0
    port: 8888
    access-log:
      enabled: true
      exclude-pattern: "/q/health/.*"

  grpc:
    server:
      use-separate-server: false
      enable-reflection-service: true
